from enum import Enum
from .monster_types import (
    MONSTER_TYPE,
    MONSTER_TYPE_NOMAL,
    MONSTER_TYPE_FIRE,
    MONSTER_TYPE_WATER,
    MONSTER_TYPE_GRASS,
    MONSTER_TYPE_ELECTRIC,
    MONSTER_TYPE_ICE,
    MONSTER_TYPE_FIGHTING,
    MONSTER_TYPE_POISON,
    MONSTER_TYPE_GROUND,
    MONSTER_TYPE_FLYING,
    MONSTER_TYPE_PSYCHIC,
    MONSTER_TYPE_BUG,
    MONSTER_TYPE_ROCK,
    MONSTER_TYPE_GHOST,
    MONSTER_TYPE_DRAGON,
    MONSTER_TYPE_DARK,
    MONSTER_TYPE_STEEL,
    MONSTER_TYPE_FAIRY,
)


class DamageRate(Enum):
    NOT_EFFECTIVE_X_4 = 0.25
    NOT_EFFECTIVE_X_2 = 0.5
    NONE = 0
    NORMAL = 1
    EFFECTIVE_X_2 = 2
    EFFECTIVE_X_4 = 4

    def __mul__(self, other):
        calced = self.value * other.value
        try:
            return DamageRate(calced)
        except ValueError:
            raise ValueError("could not mul")

    def serialize(self):
        return self.value


class MONSTER_TYPE_COMPATIBILITY(object):
    defence_type = MONSTER_TYPE
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.NORMAL,
        MONSTER_TYPE_WATER: DamageRate.NORMAL,
        MONSTER_TYPE_GRASS: DamageRate.NORMAL,
        MONSTER_TYPE_ELECTRIC: DamageRate.NORMAL,
        MONSTER_TYPE_ICE: DamageRate.NORMAL,
        MONSTER_TYPE_FIGHTING: DamageRate.NORMAL,
        MONSTER_TYPE_POISON: DamageRate.NORMAL,
        MONSTER_TYPE_GROUND: DamageRate.NORMAL,
        MONSTER_TYPE_FLYING: DamageRate.NORMAL,
        MONSTER_TYPE_PSYCHIC: DamageRate.NORMAL,
        MONSTER_TYPE_BUG: DamageRate.NORMAL,
        MONSTER_TYPE_ROCK: DamageRate.NORMAL,
        MONSTER_TYPE_GHOST: DamageRate.NONE,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.NORMAL,
        MONSTER_TYPE_FAIRY: DamageRate.NORMAL,
    }

    @classmethod
    def get_damage_rate(cls, type):
        return cls.compatibility.get(type)


class MONSTER_TYPE_COMPATIBILITY_NOMAL(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_NOMAL
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.NORMAL,
        MONSTER_TYPE_WATER: DamageRate.NORMAL,
        MONSTER_TYPE_GRASS: DamageRate.NORMAL,
        MONSTER_TYPE_ELECTRIC: DamageRate.NORMAL,
        MONSTER_TYPE_ICE: DamageRate.NORMAL,
        MONSTER_TYPE_FIGHTING: DamageRate.NORMAL,
        MONSTER_TYPE_POISON: DamageRate.NORMAL,
        MONSTER_TYPE_GROUND: DamageRate.NORMAL,
        MONSTER_TYPE_FLYING: DamageRate.NORMAL,
        MONSTER_TYPE_PSYCHIC: DamageRate.NORMAL,
        MONSTER_TYPE_BUG: DamageRate.NORMAL,
        MONSTER_TYPE_ROCK: DamageRate.NORMAL,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.NORMAL,
        MONSTER_TYPE_FAIRY: DamageRate.NORMAL,
    }


class MONSTER_TYPE_COMPATIBILITY_FIRE(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_FIRE
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_WATER: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_GRASS: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ELECTRIC: DamageRate.NORMAL,
        MONSTER_TYPE_ICE: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_FIGHTING: DamageRate.NORMAL,
        MONSTER_TYPE_POISON: DamageRate.NORMAL,
        MONSTER_TYPE_GROUND: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_FLYING: DamageRate.NORMAL,
        MONSTER_TYPE_PSYCHIC: DamageRate.NORMAL,
        MONSTER_TYPE_BUG: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ROCK: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_FAIRY: DamageRate.NOT_EFFECTIVE_X_2,
    }


class MONSTER_TYPE_COMPATIBILITY_WATER(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_WATER
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_WATER: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_GRASS: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_ELECTRIC: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_ICE: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_FIGHTING: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_POISON: DamageRate.NORMAL,
        MONSTER_TYPE_GROUND: DamageRate.NORMAL,
        MONSTER_TYPE_FLYING: DamageRate.NORMAL,
        MONSTER_TYPE_PSYCHIC: DamageRate.NORMAL,
        MONSTER_TYPE_BUG: DamageRate.NORMAL,
        MONSTER_TYPE_ROCK: DamageRate.NORMAL,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_FAIRY: DamageRate.NORMAL,
    }


class MONSTER_TYPE_COMPATIBILITY_GRASS(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_GRASS
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_WATER: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_GRASS: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ELECTRIC: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ICE: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_FIGHTING: DamageRate.NORMAL,
        MONSTER_TYPE_POISON: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_GROUND: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_FLYING: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_PSYCHIC: DamageRate.NORMAL,
        MONSTER_TYPE_BUG: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_ROCK: DamageRate.NORMAL,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.NORMAL,
        MONSTER_TYPE_FAIRY: DamageRate.NORMAL,
    }


class MONSTER_TYPE_COMPATIBILITY_ELECTRIC(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_ELECTRIC
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.NORMAL,
        MONSTER_TYPE_WATER: DamageRate.NORMAL,
        MONSTER_TYPE_GRASS: DamageRate.NORMAL,
        MONSTER_TYPE_ELECTRIC: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ICE: DamageRate.NORMAL,
        MONSTER_TYPE_FIGHTING: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_POISON: DamageRate.NORMAL,
        MONSTER_TYPE_GROUND: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_FLYING: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_PSYCHIC: DamageRate.NORMAL,
        MONSTER_TYPE_BUG: DamageRate.NORMAL,
        MONSTER_TYPE_ROCK: DamageRate.NORMAL,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_FAIRY: DamageRate.NORMAL,
    }


class MONSTER_TYPE_COMPATIBILITY_ICE(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_ICE
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_WATER: DamageRate.NORMAL,
        MONSTER_TYPE_GRASS: DamageRate.NORMAL,
        MONSTER_TYPE_ELECTRIC: DamageRate.NORMAL,
        MONSTER_TYPE_ICE: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_FIGHTING: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_POISON: DamageRate.NORMAL,
        MONSTER_TYPE_GROUND: DamageRate.NORMAL,
        MONSTER_TYPE_FLYING: DamageRate.NORMAL,
        MONSTER_TYPE_PSYCHIC: DamageRate.NORMAL,
        MONSTER_TYPE_BUG: DamageRate.NORMAL,
        MONSTER_TYPE_ROCK: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_FAIRY: DamageRate.NORMAL,
    }


class MONSTER_TYPE_COMPATIBILITY_FIGHTING(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_FIGHTING
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.NORMAL,
        MONSTER_TYPE_WATER: DamageRate.NORMAL,
        MONSTER_TYPE_GRASS: DamageRate.NORMAL,
        MONSTER_TYPE_ELECTRIC: DamageRate.NORMAL,
        MONSTER_TYPE_ICE: DamageRate.NORMAL,
        MONSTER_TYPE_FIGHTING: DamageRate.NORMAL,
        MONSTER_TYPE_POISON: DamageRate.NORMAL,
        MONSTER_TYPE_GROUND: DamageRate.NORMAL,
        MONSTER_TYPE_FLYING: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_PSYCHIC: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_BUG: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ROCK: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_STEEL: DamageRate.NORMAL,
        MONSTER_TYPE_FAIRY: DamageRate.EFFECTIVE_X_2,
    }


class MONSTER_TYPE_COMPATIBILITY_POISON(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_POISON
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.NORMAL,
        MONSTER_TYPE_WATER: DamageRate.NORMAL,
        MONSTER_TYPE_GRASS: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ELECTRIC: DamageRate.NORMAL,
        MONSTER_TYPE_ICE: DamageRate.NORMAL,
        MONSTER_TYPE_FIGHTING: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_POISON: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_GROUND: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_FLYING: DamageRate.NORMAL,
        MONSTER_TYPE_PSYCHIC: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_BUG: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ROCK: DamageRate.NORMAL,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.NORMAL,
        MONSTER_TYPE_FAIRY: DamageRate.NOT_EFFECTIVE_X_2,
    }


class MONSTER_TYPE_COMPATIBILITY_GROUND(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_GROUND
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.NORMAL,
        MONSTER_TYPE_WATER: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_GRASS: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_ELECTRIC: DamageRate.NONE,
        MONSTER_TYPE_ICE: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_FIGHTING: DamageRate.NORMAL,
        MONSTER_TYPE_POISON: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_GROUND: DamageRate.NORMAL,
        MONSTER_TYPE_FLYING: DamageRate.NORMAL,
        MONSTER_TYPE_PSYCHIC: DamageRate.NORMAL,
        MONSTER_TYPE_BUG: DamageRate.NORMAL,
        MONSTER_TYPE_ROCK: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.NORMAL,
        MONSTER_TYPE_FAIRY: DamageRate.NORMAL,
    }


class MONSTER_TYPE_COMPATIBILITY_FLYING(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_FLYING
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.NORMAL,
        MONSTER_TYPE_WATER: DamageRate.NORMAL,
        MONSTER_TYPE_GRASS: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ELECTRIC: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_ICE: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_FIGHTING: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_POISON: DamageRate.NORMAL,
        MONSTER_TYPE_GROUND: DamageRate.NONE,
        MONSTER_TYPE_FLYING: DamageRate.NORMAL,
        MONSTER_TYPE_PSYCHIC: DamageRate.NORMAL,
        MONSTER_TYPE_BUG: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ROCK: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_GHOST: DamageRate.NONE,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.NORMAL,
        MONSTER_TYPE_FAIRY: DamageRate.NORMAL,
    }


class MONSTER_TYPE_COMPATIBILITY_PSYCHIC(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_PSYCHIC
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.NORMAL,
        MONSTER_TYPE_WATER: DamageRate.NORMAL,
        MONSTER_TYPE_GRASS: DamageRate.NORMAL,
        MONSTER_TYPE_ELECTRIC: DamageRate.NORMAL,
        MONSTER_TYPE_ICE: DamageRate.NORMAL,
        MONSTER_TYPE_FIGHTING: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_POISON: DamageRate.NORMAL,
        MONSTER_TYPE_GROUND: DamageRate.NORMAL,
        MONSTER_TYPE_FLYING: DamageRate.NORMAL,
        MONSTER_TYPE_PSYCHIC: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_BUG: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_ROCK: DamageRate.NORMAL,
        MONSTER_TYPE_GHOST: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_STEEL: DamageRate.NORMAL,
        MONSTER_TYPE_FAIRY: DamageRate.NORMAL,
    }


class MONSTER_TYPE_COMPATIBILITY_BUG(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_BUG
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_WATER: DamageRate.NORMAL,
        MONSTER_TYPE_GRASS: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ELECTRIC: DamageRate.NORMAL,
        MONSTER_TYPE_ICE: DamageRate.NORMAL,
        MONSTER_TYPE_FIGHTING: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_POISON: DamageRate.NORMAL,
        MONSTER_TYPE_GROUND: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_FLYING: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_PSYCHIC: DamageRate.NORMAL,
        MONSTER_TYPE_BUG: DamageRate.NORMAL,
        MONSTER_TYPE_ROCK: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.NORMAL,
        MONSTER_TYPE_FAIRY: DamageRate.NORMAL,
    }


class MONSTER_TYPE_COMPATIBILITY_ROCK(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_ROCK
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_FIRE: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_WATER: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_GRASS: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_ELECTRIC: DamageRate.NORMAL,
        MONSTER_TYPE_ICE: DamageRate.NORMAL,
        MONSTER_TYPE_FIGHTING: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_POISON: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_GROUND: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_FLYING: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_PSYCHIC: DamageRate.NORMAL,
        MONSTER_TYPE_BUG: DamageRate.NORMAL,
        MONSTER_TYPE_ROCK: DamageRate.NORMAL,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_FAIRY: DamageRate.NORMAL,
    }


class MONSTER_TYPE_COMPATIBILITY_GHOST(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_GHOST
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NONE,
        MONSTER_TYPE_FIRE: DamageRate.NORMAL,
        MONSTER_TYPE_WATER: DamageRate.NORMAL,
        MONSTER_TYPE_GRASS: DamageRate.NORMAL,
        MONSTER_TYPE_ELECTRIC: DamageRate.NORMAL,
        MONSTER_TYPE_ICE: DamageRate.NORMAL,
        MONSTER_TYPE_FIGHTING: DamageRate.NONE,
        MONSTER_TYPE_POISON: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_GROUND: DamageRate.NORMAL,
        MONSTER_TYPE_FLYING: DamageRate.NORMAL,
        MONSTER_TYPE_PSYCHIC: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_BUG: DamageRate.NORMAL,
        MONSTER_TYPE_ROCK: DamageRate.NORMAL,
        MONSTER_TYPE_GHOST: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_STEEL: DamageRate.NORMAL,
        MONSTER_TYPE_FAIRY: DamageRate.NORMAL,
    }


class MONSTER_TYPE_COMPATIBILITY_DRAGON(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_DRAGON
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_WATER: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_GRASS: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ELECTRIC: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ICE: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_FIGHTING: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_POISON: DamageRate.NORMAL,
        MONSTER_TYPE_GROUND: DamageRate.NORMAL,
        MONSTER_TYPE_FLYING: DamageRate.NORMAL,
        MONSTER_TYPE_PSYCHIC: DamageRate.NORMAL,
        MONSTER_TYPE_BUG: DamageRate.NORMAL,
        MONSTER_TYPE_ROCK: DamageRate.NORMAL,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.NORMAL,
        MONSTER_TYPE_FAIRY: DamageRate.EFFECTIVE_X_2,
    }


class MONSTER_TYPE_COMPATIBILITY_DARK(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_DARK
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.NORMAL,
        MONSTER_TYPE_WATER: DamageRate.NORMAL,
        MONSTER_TYPE_GRASS: DamageRate.NORMAL,
        MONSTER_TYPE_ELECTRIC: DamageRate.NORMAL,
        MONSTER_TYPE_ICE: DamageRate.NORMAL,
        MONSTER_TYPE_FIGHTING: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_POISON: DamageRate.NORMAL,
        MONSTER_TYPE_GROUND: DamageRate.NORMAL,
        MONSTER_TYPE_FLYING: DamageRate.NORMAL,
        MONSTER_TYPE_PSYCHIC: DamageRate.NONE,
        MONSTER_TYPE_BUG: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_ROCK: DamageRate.NORMAL,
        MONSTER_TYPE_GHOST: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_DRAGON: DamageRate.NORMAL,
        MONSTER_TYPE_DARK: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_STEEL: DamageRate.NORMAL,
        MONSTER_TYPE_FAIRY: DamageRate.EFFECTIVE_X_2,
    }


class MONSTER_TYPE_COMPATIBILITY_STEEL(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_STEEL
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_FIRE: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_WATER: DamageRate.NORMAL,
        MONSTER_TYPE_GRASS: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ELECTRIC: DamageRate.NORMAL,
        MONSTER_TYPE_ICE: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_FIGHTING: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_POISON: DamageRate.NORMAL,
        MONSTER_TYPE_GROUND: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_FLYING: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_PSYCHIC: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_BUG: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ROCK: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_DARK: DamageRate.NORMAL,
        MONSTER_TYPE_STEEL: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_FAIRY: DamageRate.NOT_EFFECTIVE_X_2,
    }


class MONSTER_TYPE_COMPATIBILITY_FAIRY(MONSTER_TYPE_COMPATIBILITY):
    defence_type = MONSTER_TYPE_FAIRY
    compatibility = {
        MONSTER_TYPE: DamageRate.NORMAL,
        MONSTER_TYPE_NOMAL: DamageRate.NORMAL,
        MONSTER_TYPE_FIRE: DamageRate.NORMAL,
        MONSTER_TYPE_WATER: DamageRate.NORMAL,
        MONSTER_TYPE_GRASS: DamageRate.NORMAL,
        MONSTER_TYPE_ELECTRIC: DamageRate.NORMAL,
        MONSTER_TYPE_ICE: DamageRate.NORMAL,
        MONSTER_TYPE_FIGHTING: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_POISON: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_GROUND: DamageRate.NORMAL,
        MONSTER_TYPE_FLYING: DamageRate.NORMAL,
        MONSTER_TYPE_PSYCHIC: DamageRate.NORMAL,
        MONSTER_TYPE_BUG: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_ROCK: DamageRate.NORMAL,
        MONSTER_TYPE_GHOST: DamageRate.NORMAL,
        MONSTER_TYPE_DRAGON: DamageRate.NONE,
        MONSTER_TYPE_DARK: DamageRate.NOT_EFFECTIVE_X_2,
        MONSTER_TYPE_STEEL: DamageRate.EFFECTIVE_X_2,
        MONSTER_TYPE_FAIRY: DamageRate.NORMAL,
    }


monster_type_compatibilities = [
    MONSTER_TYPE_COMPATIBILITY,
    MONSTER_TYPE_COMPATIBILITY_NOMAL,
    MONSTER_TYPE_COMPATIBILITY_FIRE,
    MONSTER_TYPE_COMPATIBILITY_WATER,
    MONSTER_TYPE_COMPATIBILITY_GRASS,
    MONSTER_TYPE_COMPATIBILITY_ELECTRIC,
    MONSTER_TYPE_COMPATIBILITY_ICE,
    MONSTER_TYPE_COMPATIBILITY_FIGHTING,
    MONSTER_TYPE_COMPATIBILITY_POISON,
    MONSTER_TYPE_COMPATIBILITY_GROUND,
    MONSTER_TYPE_COMPATIBILITY_FLYING,
    MONSTER_TYPE_COMPATIBILITY_PSYCHIC,
    MONSTER_TYPE_COMPATIBILITY_BUG,
    MONSTER_TYPE_COMPATIBILITY_ROCK,
    MONSTER_TYPE_COMPATIBILITY_GHOST,
    MONSTER_TYPE_COMPATIBILITY_DRAGON,
    MONSTER_TYPE_COMPATIBILITY_DARK,
    MONSTER_TYPE_COMPATIBILITY_STEEL,
    MONSTER_TYPE_COMPATIBILITY_FAIRY,
]


monster_type_to_monster_type_compatibility = {
    monster_type_compatibility.defence_type: monster_type_compatibility
    for monster_type_compatibility in monster_type_compatibilities
}


def get_compatibility_with_monster_type(monster_type):
    compatibility = monster_type_to_monster_type_compatibility.get(monster_type)
    if compatibility is None:
        return MONSTER_TYPE_COMPATIBILITY
    return compatibility
