# Generated by Django 2.2.1 on 2019-12-17 07:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="PokemonBase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.TextField()),
                ("name", models.TextField()),
                ("form", models.TextField()),
                ("is_mega_evolution", models.BooleanField(default=False)),
                ("evolutions", django.contrib.postgres.fields.jsonb.JSONField()),
                ("types", django.contrib.postgres.fields.jsonb.JSONField()),
                ("abilities", django.contrib.postgres.fields.jsonb.JSONField()),
                ("hidden_abilities", django.contrib.postgres.fields.jsonb.JSONField()),
                ("stats", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        )
    ]
