# Generated by Django 2.2.1 on 2019-12-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("app", "0002_pokemonbase")]

    operations = [
        migrations.AlterModelOptions(name="pokemon", options={"ordering": ["id"]}),
        migrations.AlterModelOptions(name="pokemonbase", options={"ordering": ["no"]}),
        migrations.AlterModelTable(name="pokemon", table="app_pokemon"),
        migrations.AlterModelTable(name="pokemonbase", table="app_pokemon_base"),
    ]
