# Generated by Django 2.2.1 on 2019-12-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("app", "0003_auto_20191217_1730")]

    operations = [
        migrations.AlterModelOptions(name="pokemonbase", options={"ordering": ["id"]})
    ]
